Fix the pandas dependency requirement.
Currently tests/test_parallel invokes pandas.DataFrame.sort_values
which is only available in 0.17.0

http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.sort_values.html?highlight=sort_values#pandas.DataFrame.sort_values

so a user cannot run the tests with any lower version, which returns

E           AttributeError: 'DataFrame' object has no attribute 'sort_values'

Also, ensure code in test_parallel.py has consistent formatting in
two places that is both consistent with itself, and the bdbcontrib
conventions.